---
name: Nhat
surname: Dang
position: "Data Analyst"
address: "Quang Trung St., Ward 10, Go Vap District, Ho Chi Minh City, Vietnam"
phone: +84 0354883673
profilepic: mariecurie.jpg
www: https://www.linkedin.com/in/dangnhatsimon/
email: "dangnhatsimon@gmail.com"
twitter: https://twitter.com/dangnhatsimon
github: https://github.com/dangnhatsimon
linkedin: https://www.linkedin.com/in/dangnhatsimon/
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "I'm changing career to entry-level data analytics professional, completed the Google Data Analytics Professional Certificate. With good understanding and proficiency of platforms for effective data analyses, including SQL, Spreadsheet, Power BI, Tableau and R. Strong communication, organizational and analytical skills, statistics and probability."
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Informal studies", "1889-91", "Flying University", "Warsaw, Poland",
  "Master of Physics", "1893", "Sorbonne Université", "Paris, France",
  "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

